services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data/logs:/app/data/logs
            - ./src:/app/src
        environment:
            - TRADE_SERVER_URL=${TRADE_SERVER_URL:-http://195.7.7.93:18080}
            - ENVIRONMENT=local
        networks:
            - app-net
        restart: unless-stopped

    api:
        build:
            context: ./web_api_config
            dockerfile: Dockerfile
        volumes:
            - ./config:/var/www/html/config
            - ./data/logs:/var/www/html/data/logs
            - ./src:/var/www/html/src
            - ./web_api_config/.htaccess:/var/www/html/.htaccess
        environment:
            - TRADE_SERVER_URL=${TRADE_SERVER_URL:-http://195.7.7.93:18080}
        ports:
            - '8080:80'
        networks:
            - app-net
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
        ports:
            - '80:80'
        depends_on:
            - api
        networks:
            - app-net
        restart: unless-stopped

networks:
    app-net:
        driver: bridge
