services:
    backend-dev:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./src:/app/src
            - ./router.php:/app/router.php
            - ./index.php:/app/index.php
            - ./public:/app/public
        environment:
            - TRADE_SERVER_URL=http://164.68.117.90:18080
            - ENVIRONMENT=dev
            - DEAD_WATCHER_URLS=http://164.68.117.90:5503/dead-watcher/heartbeat # if you have 2 or more instances of dead-watcher, you can add this via comma separated values
        ports:
            - '5501:8080' # Порт 5501 для Dev-середовища
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-backend-dev
        command: both # Запуск і сервера, і менеджера ботів

    frontend-dev:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        environment:
            - API_BASE_URL=/api
            - SWAGGER_URL=/swagger-ui
            - ENVIRONMENT=dev
        ports:
            - '5502:80' # Порт 5502 для Dev-середовища
        depends_on:
            - backend-dev
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-frontend-dev

networks:
    app-dev-net:
        driver: bridge
