version: '3'

services:
    backend-demo:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./src:/app/src
            - ./router.php:/app/router.php
            - ./index.php:/app/index.php
            - ./public:/app/public
        environment:
            - TRADE_SERVER_URL=http://164.68.117.90:18080
            - ENVIRONMENT=demo
        ports:
            - '6501:8080' # Порт 6501 для Demo-середовища
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-backend-demo
        command: php -S 0.0.0.0:8080 router.php # Запуск PHP-сервера з використанням router.php

    frontend-demo:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-demo.conf:/etc/nginx/conf.d/default.conf
        environment:
            - API_BASE_URL=/api
            - SWAGGER_URL=/swagger-ui
            - ENVIRONMENT=demo
        ports:
            - '6502:80' # Порт 6502 для Demo-середовища
        depends_on:
            - backend-demo
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-frontend-demo

networks:
    app-demo-net:
        driver: bridge
