services:
    backend-dev:
        build:
            context: .
            dockerfile: backend/Dockerfile
            args:
                - ENVIRONMENT=dev
        volumes:
            # Не монтуємо конфігураційні файли
            # - ./config:/app/config
            - ./data/logs:/app/data/logs
            - ./data/pids:/app/data/pids
            - ./src:/app/src
            - ./router.php:/app/router.php
            - ./index.php:/app/index.php
            - ./public:/app/public
        environment:
            - TRADE_SERVER_URL=http://195.7.7.93:18080
            - ENVIRONMENT=dev
        ports:
            - '5501:8080' # Порт 5501 для Dev-середовища
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-backend-dev
        command: php -S 0.0.0.0:8080 router.php # Запуск PHP-сервера з використанням router.php

    frontend-dev:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        environment:
            - API_BASE_URL=/api
            - SWAGGER_URL=/swagger-ui
            - ENVIRONMENT=dev
        ports:
            - '5502:80' # Порт 5502 для Dev-середовища
        depends_on:
            - backend-dev
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-frontend-dev

networks:
    app-dev-net:
        driver: bridge
