version: '3'

services:
    backend-dev:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./src:/app/src
        environment:
            - TRADE_SERVER_URL=http://195.7.7.93:18080
        ports:
            - '8080:8080' # Основний порт для бекенду та API
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-backend-dev
        command: php -S 0.0.0.0:8080 -t src/ # Запуск PHP-сервера на порту 8080

    frontend-dev:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80' # Стандартний порт для фронтенду
        depends_on:
            - backend-dev
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-frontend-dev

networks:
    app-dev-net:
        driver: bridge
