version: '3'

services:
    trading-bot:
        build:
            context: .
            dockerfile: Dockerfile.manager
        image: trading-bot-manager:latest
        volumes:
            - ./data:/app/data
        ports:
            - '5560:8080'
        restart: unless-stopped
        command: php src/core/TradingBotManager.php
        networks:
            - bot-network

    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: trading-bot-api:latest
        volumes:
            - ./data:/app/data
        ports:
            - '5561:8080'
        restart: unless-stopped
        command: php -S 0.0.0.0:8080 -t /app
        networks:
            - bot-network

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        image: trading-bot-frontend:latest
        volumes:
            - ./frontend:/app/frontend
        ports:
            - '5562:80'
        restart: unless-stopped
        command: php -S 0.0.0.0:80 -t frontend
        networks:
            - bot-network

networks:
    bot-network:
        driver: bridge
