version: '3'

services:
    backend-demo:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./src:/app/src
        environment:
            - TRADE_SERVER_URL=http://164.68.117.90:18080
        ports:
            - '8090:8080' # Альтернативний порт для бекенду та API в демо-середовищі
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-backend-demo
        command: php -S 0.0.0.0:8080 -t src/ # Запуск PHP-сервера на порту 8080

    frontend-demo:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-demo.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8082:80' # Альтернативний порт для фронтенду в демо-середовищі
        depends_on:
            - backend-demo
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-frontend-demo

networks:
    app-demo-net:
        driver: bridge
