version: '3'

services:
    backend-demo:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./src:/app/src
        environment:
            - TRADE_SERVER_URL=http://164.68.117.90:18080
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-backend-demo

    api-demo:
        build:
            context: .
            dockerfile: api/Dockerfile
        volumes:
            - ./config:/var/www/html/config
            - ./data:/var/www/html/data
            - ./src:/var/www/html/src
            - ./.htaccess:/var/www/html/.htaccess
        environment:
            - TRADE_SERVER_URL=http://164.68.117.90:18080
        ports:
            - '8082:80'
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-api-demo

    frontend-demo:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-demo.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8002:80'
        depends_on:
            - api-demo
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-frontend-demo

networks:
    app-demo-net:
        driver: bridge
