version: '3'

services:
    backend-dev:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./src:/app/src
        environment:
            - TRADE_SERVER_URL=http://195.7.7.93:18080
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-backend-dev

    api-dev:
        build:
            context: .
            dockerfile: api/Dockerfile
        volumes:
            - ./config:/var/www/html/config
            - ./data:/var/www/html/data
            - ./src:/var/www/html/src
            - ./.htaccess:/var/www/html/.htaccess
        environment:
            - TRADE_SERVER_URL=http://195.7.7.93:18080
        ports:
            - '8081:80'
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-api-dev

    frontend-dev:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8001:80'
        depends_on:
            - api-dev
        networks:
            - app-dev-net
        restart: unless-stopped
        container_name: trading-bot-frontend-dev

networks:
    app-dev-net:
        driver: bridge
