version: '3'

services:
    backend-demo:
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./src:/app/src
            - ./router.php:/app/router.php
            - ./index.php:/app/index.php
            - ./public:/app/public
            - ./data/logs:/app/data/logs
        environment:
            - TRADE_SERVER_URL=http://195.7.7.93:18080
            - ENVIRONMENT=demo
            - DEAD_WATCHER_URLS=http://164.68.117.90:6503/dead-watcher/heartbeat # if you have 2 or more instances of dead-watcher, you can add this via comma separated values
        ports:
            - '6501:8080' # Port 6501 for Demo environment
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-backend-demo
        command: both # Start both server and bot manager

    frontend-demo:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/nginx-demo.conf:/etc/nginx/conf.d/default.conf
        environment:
            - API_BASE_URL=/api
            - SWAGGER_URL=/swagger-ui
            - ENVIRONMENT=demo
        ports:
            - '6502:80' # Port 6502 for Demo environment
        depends_on:
            - backend-demo
        networks:
            - app-demo-net
        restart: unless-stopped
        container_name: trading-bot-frontend-demo

networks:
    app-demo-net:
        driver: bridge
